# SQLite version 3.x
# gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  #adapter: postgresql
  #encoding: unicode
  #database: catarse_development
  #pool: 5
  #username: 
  #password: 
  
 
 #adapter: mysql
  #adapter: mysql2
  #encoding: utf8
  #database: catarse_development
  #username: 
  #password: 
  #host: localhost 
  #port: 3306
  #timeout: 5000
  
    adapter: postgresql
    encoding: utf-8
    database: catarse_development
    pool: 5
    username: postgres
    password: 
    host: localhost
    port: 5432 
    
production:
  adapter: postgresql
  encoding: utf-8
  database: catarse_production
  pool: 5
  username: postgres